# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 17:19
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='apps_celeryscan',
            fields=[
                ('id_key', models.AutoField(primary_key = True)),
                ('json_results', models.CharField(max_length = 20000, null=True, blank=True)),
                ('img_link', models.CharField(max_length = 20000, null=True, blank=True)),
                ('video_link', models.CharField(max_length = 20000, null=True, blank=True)),
                ('is_complete', models.BooleanField(default = False)),
            ],
        ),
        
    ]